server:
  port: 8088

# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: config-client
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8888