server:
  port: 8086

# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: feign

eureka:
  client:
    serviceUrl:
      #      指定服务注册中心的地址
      defaultZone: http://localhost:8080/eureka/

feign:
  hystrix:
    enabled: true
