server:
  port: 8087

# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lianpeixin/spring-cloud-config.git
          search-paths: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
